### ISSUE TITLE
After payment (mobile) not directing to "order received page"

### ISSUE THREAD

**Issue by Albertus58** [KoenPaas/xumm-for-woocommerce#28]
same problem as closed issue #24 and #25  still exists
removed plugin, installed newest version but same problem on mobile browsers. 
(On PC OK)
Also now error in XUMM app screen: Error Unable to open return url!

**Comment by KoenPaas** [comment]
@Albertus58 are you using another browser then the default safari on your iPhone?

Possible cause is could be this related issue: https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/270

**Comment by Albertus58** [comment]
I had chosen Chrome as std browser indeed. 
Put it back to Safari and now everything works fine with Safari!
If I use Chrome or Firefox now to order, the order received page opens in Safari. 
Chrome/Firefox keeps waiting forever like my earlier screenshot shows

**Comment by KoenPaas** [comment]
Closed due to a XUMM app bug reference:
https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/270
